baseURL = 'https://kucharski.ai/'
languageCode = 'en'
title = 'Marcin Kucharski'
enableRobotsTXT = true

[params]
  description = "A geek with ADHD who'd love to work with AI until 2 AM — but is too old for that."
  author = "Marcin Kucharski"
  email = "hello@kucharski.ai"
  linkedin = "https://linkedin.com/in/makucharski"

[outputs]
  home = ["HTML", "RSS"]

[outputFormats.RSS]
  mediaType = "application/rss+xml"
  baseName = "feed"

[taxonomies]
  tag = "tags"

[markup.goldmark.renderer]
  unsafe = true
