baseURL = 'https://kucharski.ai/'
languageCode = 'en'
title = 'Marcin Kucharski'

[params]
  description = "A geek with ADHD who'd love to work with AI until 2 AM — but is too old for that."
  author = "Marcin Kucharski"
  email = "hello@kucharski.ai"
  linkedin = "https://linkedin.com/in/makucharski"

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML"]

[markup.goldmark.renderer]
  unsafe = true
